/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ballsortpuzzle;

import busca.BuscaProfundidade;
import busca.Nodo;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
  */
public class carregaProfundidade extends javax.swing.JFrame {

    /**
     * Creates new form carregaProfundidade
     */
    String nodo;
    private final inicioView inicioview;
    static Nodo no;
    Nodo noAux;
    int profundidade;
    static int posicao;
    static int cont;
    ArrayList<Nodo> arrayNo = new ArrayList<>();

    public carregaProfundidade(inicioView inicioview) {
        this.inicioview = inicioview;
        initComponents();
    }
    
        public void carregamento(){
        final telaLoading loading = new telaLoading();
        loading.setVisible(true);
        Thread thread = new Thread(){
            
            @Override
            public void run(){
                solucaoProfundidade();
                loading.dispose();
                setVisible(true);
                btnFinal.setEnabled(false);
                btnSeguir.setEnabled(false);
            }
        };
        thread.start();
    }
        
    public void solucaoProfundidade() {
        try {
            BallSortPuzzle ballPuzzle = new BallSortPuzzle(inicioview.getnovoEstadoBallPuzzle());
            var bLarg = new BuscaProfundidade<BallSortPuzzle>();

            Nodo n = bLarg.busca(ballPuzzle);

            // chama busca em profundidade
            n = new BuscaProfundidade<BallSortPuzzle>().busca(ballPuzzle);
            if (n == null) {
           JOptionPane.showMessageDialog(null, "Nao foi encontrada uma solucao para o puzzle selecionado", "Solucao nao encontrada", JOptionPane.ERROR_MESSAGE);
            } else {
                numJogadas.setText(String.valueOf(n.getProfundidade()));
            
                noAux = n;
            for(int i = 0; i < n.getProfundidade()+1; i++){
                arrayNo.add(noAux);
                noAux = noAux.getPai();
            }
            
            profundidade = n.getProfundidade();
            no = arrayNo.get(0);
            nodo = String.valueOf(n);
            ((Painel)this.jPanel1).setNodo(nodo);
            ((Painel)this.jPanel1).setTamanhoJogo(inicioview.getnovoEstadoBallPuzzle().size());
            }
        } catch (Exception e) {
        }
    }
    
        public void avancaPosicao(){
        for(int i = 0; i < arrayNo.size(); i ++){
            if(arrayNo.get(i).toString().equals(no.toString())){
                posicao = i;
            }
        }
        if(posicao - 1 > 0){
            no = arrayNo.get(posicao - 1);
        }else
            no = arrayNo.get(0);
        
    }
    
    public void desabilitaBotoesSeguir(){
        if(posicao - 1 <= 0){
            btnSeguir.setEnabled(false);
            btnFinal.setEnabled(false);
            btnInicio.setEnabled(true);
            btnVoltar.setEnabled(true);
        }
        else{
            btnVoltar.setEnabled(true);
            btnInicio.setEnabled(true);
            btnSeguir.setEnabled(true);
            btnFinal.setEnabled(true);
        }
    }
    
    public void desabilitaBotoesVoltar(){
        if(no.getPai() == null){
            btnInicio.setEnabled(false);
            btnVoltar.setEnabled(false);
            btnSeguir.setEnabled(true);
            btnFinal.setEnabled(true);
        }
        else{
            btnSeguir.setEnabled(true);
            btnFinal.setEnabled(true);
            btnInicio.setEnabled(true);
            btnVoltar.setEnabled(true);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numJogadas = new javax.swing.JLabel();
        labelJogadas = new javax.swing.JLabel();
        jPanel1 = new Painel();
        btnFinal = new javax.swing.JButton();
        btnSeguir = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelJogadas.setText("Quantidade de jogadas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );

        btnFinal.setText(">>|");
        btnFinal.addActionListener(this::btnFinalActionPerformed);

        btnSeguir.setMnemonic('>');
        btnSeguir.setText(">>");
        btnSeguir.addActionListener(this::btnSeguirActionPerformed);

        btnVoltar.setText("<<");
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);

        btnInicio.setText("|<<");
        btnInicio.addActionListener(this::btnInicioActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeguir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelJogadas)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(numJogadas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelJogadas)
                        .addGap(4, 4, 4)
                        .addComponent(numJogadas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSeguir)
                            .addComponent(btnVoltar)
                            .addComponent(btnInicio)
                            .addComponent(btnFinal))))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalActionPerformed
        cont = 0;
        no = arrayNo.get(cont);
        nodo = String.valueOf(no);
        ((Painel)this.jPanel1).setNodo(nodo);
        ((Painel)this.jPanel1).desenhaBolinha();
        this.jPanel1.repaint();
         btnVoltar.setEnabled(true);
         btnInicio.setEnabled(true);
         btnFinal.setEnabled(false);
         btnSeguir.setEnabled(false);
    }//GEN-LAST:event_btnFinalActionPerformed

    private void btnSeguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguirActionPerformed
        avancaPosicao();
        nodo = String.valueOf(no);
        ((Painel)this.jPanel1).setNodo(nodo);
        ((Painel)this.jPanel1).desenhaBolinha();
        this.jPanel1.repaint();
        desabilitaBotoesSeguir();
    }//GEN-LAST:event_btnSeguirActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        nodo = String.valueOf(no.getPai());
        ((Painel)this.jPanel1).setNodo(nodo);
        ((Painel)this.jPanel1).desenhaBolinha();
        this.jPanel1.repaint();
        no = no.getPai();
        desabilitaBotoesVoltar();
        
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        cont = profundidade;
        no = arrayNo.get(cont);
        nodo = String.valueOf(no);
        ((Painel)this.jPanel1).setNodo(nodo);
        ((Painel)this.jPanel1).desenhaBolinha();
        this.jPanel1.repaint();
         btnVoltar.setEnabled(false);
         btnInicio.setEnabled(false);
         btnFinal.setEnabled(true);
         btnSeguir.setEnabled(true);
    }//GEN-LAST:event_btnInicioActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinal;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnSeguir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelJogadas;
    private javax.swing.JLabel numJogadas;
    // End of variables declaration//GEN-END:variables
}
