/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ballsortpuzzle;

import java.util.ArrayList;

/**
 *
 */
public final class inicioView extends javax.swing.JFrame {

    ArrayList<Tubo> novoEstadoBallPuzzle;
    
    public inicioView() {
        this.novoEstadoBallPuzzle = new ArrayList<>();
        initComponents();
        visibilidadeBotoes();
    }
    
    public void visibilidadeBotoes(){
        if(novoEstadoBallPuzzle.isEmpty()){
            btnLargura.setEnabled(false);
            btnProfundidade.setEnabled(false);
        }
        else{
            btnLargura.setEnabled(true);
            btnProfundidade.setEnabled(true);
        }
    }
    
    public ArrayList <Tubo> getnovoEstadoBallPuzzle(){
        return this.novoEstadoBallPuzzle;
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSobre = new javax.swing.JButton();
        btnProfundidade = new javax.swing.JButton();
        btnLargura = new javax.swing.JButton();
        btnCarregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSobre.setText("Sobre");
        btnSobre.addActionListener(this::btnSobreActionPerformed);

        btnProfundidade.setText("Profundidade");
        btnProfundidade.addActionListener(this::btnProfundidadeActionPerformed);

        btnLargura.setText("Largura");
        btnLargura.addActionListener(this::btnLarguraActionPerformed);

        btnCarregar.setText("Carregar");
        btnCarregar.addActionListener(this::btnCarregarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(btnCarregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLargura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProfundidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSobre)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarregar)
                    .addComponent(btnLargura)
                    .addComponent(btnProfundidade)
                    .addComponent(btnSobre))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobreActionPerformed
        sobreView sobreview = new sobreView(this);
        sobreview.setVisible(true);
    }//GEN-LAST:event_btnSobreActionPerformed

    private void btnLarguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLarguraActionPerformed
        carregaLargura carregaLargura = new carregaLargura(this);
        carregaLargura.carregamento();
    }//GEN-LAST:event_btnLarguraActionPerformed

    private void btnCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarActionPerformed
        SelecaoPuzzle selecaoPuzzle = new SelecaoPuzzle(this);
        selecaoPuzzle.setVisible(true);
    }//GEN-LAST:event_btnCarregarActionPerformed

    private void btnProfundidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfundidadeActionPerformed
        carregaProfundidade carregaProfundidade = new carregaProfundidade(this);
        carregaProfundidade.carregamento();
    }//GEN-LAST:event_btnProfundidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new inicioView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarregar;
    private javax.swing.JButton btnLargura;
    private javax.swing.JButton btnProfundidade;
    private javax.swing.JButton btnSobre;
    // End of variables declaration//GEN-END:variables
}
