/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ballsortpuzzle;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.Collections;
import java.util.LinkedList;
import java.util.Queue;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Ana e Gabriel
 */
public class SelecaoPuzzle extends javax.swing.JFrame {

    /**
     * Creates new form SelecaoPuzzle
     */
    private inicioView inicioview;
    
    Queue<String> bolas;
    int quantidadeTubos;
    //Variaveis da GUI
    
    public SelecaoPuzzle() {
        initComponents();
    }

    SelecaoPuzzle(inicioView inicioview) {
        this.inicioview = inicioview;
        initComponents();
    }
    
    public void criarTubos() {
        int testeBolas = bolas.size();
        int resto = testeBolas % 4;
        if(resto == 0){
         inicioview.getnovoEstadoBallPuzzle().clear();
        for (int i = 0; i < quantidadeTubos; i++) {
            inicioview.getnovoEstadoBallPuzzle().add(new Tubo());
        }

        for (int i = 0; i < inicioview.getnovoEstadoBallPuzzle().size() - 2; i++) {
            while (!(inicioview.getnovoEstadoBallPuzzle().get(i).isFull())) {
                String bola = bolas.remove();
                inicioview.getnovoEstadoBallPuzzle().get(i).push(bola);
            }
        }
        inicioview.visibilidadeBotoes();
        }
        else{
                       JOptionPane.showMessageDialog(null, "O puzzle selecionado nao contem 4 bolas nos tubos", "Puzzle invalido", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void testarPuzzle() throws Exception {
        //Definindo o Estado Inicial 
        criarTubos();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSelecionarPuzzle = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSelecionarPuzzle.setBackground(new java.awt.Color(0, 0, 0));
        btnSelecionarPuzzle.setForeground(new java.awt.Color(255, 255, 255));
        btnSelecionarPuzzle.setText("<html>\n<body>\n<b>SELECIONE UM PUZZLE</b>\n</body>\n</html>");
        btnSelecionarPuzzle.addActionListener(this::btnSelecionarPuzzleActionPerformed);

        jLabel1.setText("<html> <body>  <h3>REGRAS PARA IMPORTAR UM PUZZLE: </h3> 1. O Jogo BallSortPuzzle desenvolvido pelos alunos Ana Cristina Vasconcellos Reinert e Gabriel Antonio Bertoldi Perini é feito de tubos com 4 bolas. Logo, leve em consideracao que a quantidade de bolinhas no tubo SEMPRE vai ser 4. <p/> 2. A estrutura do arquivo tem de conter um inteiro e uma lista de String, sendo o valor inteiro o numero de tubos e a lista de String as bolinhas na ordem que deseja coloca-los separando-as por virgula, SEM ESPACOS ENTRE AS CORES. <p/> 3. O jogo so aceitara arquivos do tipo .txt. <p/> 4. Ao finalizar a criacao da lista de Strings, nao coloque nada ao fim da ultima cor. Ex.: Ao fim da ultima cor colocar , ou ; <p/> 5. A lista de string tem de ser NECESSARIAMENTE composta por cores no padrao hexadecimal. Ex.: para representar a cor vermelha, você poderia colocar:  #eb4034. <p/> </body> </html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecionarPuzzle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSelecionarPuzzle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionarPuzzleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarPuzzleActionPerformed
        if (evt.getSource() == btnSelecionarPuzzle) {
            //Abrindo o FileChooser
            
            JFileChooser fileChooser = new JFileChooser();
            int response = fileChooser.showOpenDialog(null);

            //Verificando se um arquivo foi selecionado 
            if (response == JFileChooser.APPROVE_OPTION) {
                //Pegando a rota do arquivo
              File puzzle = new File(fileChooser.getSelectedFile().getAbsolutePath());
             
            //Lendo o arquivo
            try {
                try (BufferedReader reader = new BufferedReader(new FileReader(puzzle))) {
                    String primeiraLinha = reader.readLine().trim();
                    //Recuperando o número de tubos
                    String[] metade = primeiraLinha.split(";");
                    quantidadeTubos = Integer.parseInt(metade[0]);

                    //Recuperando a cor de cada bolinha e as organizando na fila
                    String[] cores = metade[1].split(",");
                    bolas = new LinkedList<>();
                    //Passando as bolinhas do array para a fila
                    Collections.addAll(bolas, cores);
                }

                //Testando o Puzzle
                testarPuzzle();

            } catch (Exception ex) {
                Logger.getLogger(BallSortPuzzleGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
        }
        this.dispose();
    }//GEN-LAST:event_btnSelecionarPuzzleActionPerformed
        
    /**
     * @param args the command line arguments
     */    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSelecionarPuzzle;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
